'''
URL: http://projecteuler.net/problem=2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def getEvensSumInFibonacci(firstNumber, previousNumber, maxValue):
	
	evensSum = 0
	
	while True:
		fiboNumber = firstNumber + previousNumber
		previousNumber = firstNumber
		firstNumber = fiboNumber

		if fiboNumber >= maxValue:
			return evensSum
		elif fiboNumber % 2 == 0:
			evensSum += fiboNumber



def main():

	print getEvensSumInFibonacci(1, 0, 4000000)
	
if __name__ == '__main__':
     main()